#!/usr/bin/env node
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { ProjectEngine } from './project-engine.mjs';

const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ui-designer-mcp-'));
const projectPath = path.join(tempDir, 'sample.uiproj');
const exportPath = path.join(tempDir, 'sample-structured.json');
const exportTsPath = path.join(tempDir, 'sample-ui.ts');
const exportLuaPath = path.join(tempDir, 'sample-ui.lua');

const seedProject = {
  widgets: [],
  settings: {
    canvasWidth: 1920,
    canvasHeight: 1080,
    rulerStep: 64,
    gridSnapStep: 16,
    autoSave: false,
    controlPanelWidth: 220,
    canvasBgColor: '#1a1a1a',
    canvasBgImage: '',
  },
  resources: [],
  animations: [],
  nextAnimId: 1,
  exportConfig: {
    exportResourcesEnabled: false,
    exportResourcesPath: '',
    exportCodeEnabled: true,
    exportCodePath: '',
    selectedExportPlugin: 'json-structured-export',
    exportPlugins: [],
  },
};

await fs.writeFile(projectPath, JSON.stringify(seedProject, null, 2), 'utf8');

const engine = new ProjectEngine();
await engine.openProject(projectPath);
engine.applyActions([
  {
    type: 'createWidget',
    actionId: 'create-main-button',
    payload: {
      widgetType: 'button',
      overrides: { name: 'btnStart', text: '开始游戏', x: 300, y: 200 },
    },
  },
], { sessionId: 'e2e-session-1', dryRun: true });

const applyResult = engine.applyActions([
  {
    type: 'createWidget',
    actionId: 'create-main-button',
    payload: {
      widgetType: 'button',
      overrides: { name: 'btnStart', text: '开始游戏', x: 300, y: 200 },
    },
  },
], { sessionId: 'e2e-session-1' });

if (!applyResult.ok) {
  throw new Error(`apply actions failed: ${applyResult.errors.join('; ')}`);
}
const validateResult = engine.validate();
if (!validateResult.ok) {
  throw new Error(`validate failed: ${validateResult.diagnostics.join('; ')}`);
}
await engine.exportCode({ outputPath: exportPath, pluginId: 'json-structured-export' });
await engine.exportCode({ outputPath: exportTsPath, pluginId: 'typescript-export' });
await engine.exportCode({ outputPath: exportLuaPath, pluginId: 'lua-export' });
const auditTrail = engine.getAuditTrail(20);
if (!auditTrail.length) {
  throw new Error('audit trail should not be empty');
}

const exported = JSON.parse(await fs.readFile(exportPath, 'utf8'));
if (!exported?.widgets?.flat?.length) {
  throw new Error('exported structured JSON has no widgets');
}
if (!Array.isArray(exported?.widgets?.tree)) {
  throw new Error('exported structured JSON missing widget tree');
}
const tsOutput = await fs.readFile(exportTsPath, 'utf8');
if (!tsOutput.includes('Auto-generated by ui-designer MCP')) {
  throw new Error('typescript export content invalid');
}
const luaOutput = await fs.readFile(exportLuaPath, 'utf8');
if (!luaOutput.includes('Frame.Panel')) {
  throw new Error('lua export content invalid');
}

console.log('MCP E2E check passed');
console.log(`projectPath=${projectPath}`);
console.log(`exportPath=${exportPath}`);
